services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bo-nextjs-components
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  